### ISSUE TITLE
Missing Videos in backup2/ folder

### ISSUE THREAD

**Issue by junjiek** [baidut/PatchVQ#1]
I think some of the videos are missing under backup2/ folder. The folder only contains 27 videos and some of the videos in the csv are not available (e.g. backup2/b3.mp4 and backup2/b4.mp4)

**Comment by baidut** [comment]
@junjiek  Thank you so much for reporting the issue.
I have uploaded it again. See `backup2-total.zip` https://utexas.app.box.com/folder/127942311000?s=3x10cuh5m2r85gcjmatgagkpf2ekgqwo

Really sorry for the inconvenience!
