### ISSUE TITLE
Number of video and video duration

### ISSUE THREAD

**Issue by h4nwei** [baidut/PatchVQ#6]
Hi @baidut,

Thanks for your great effort in constructing the excellent UGC VQA dataset. I encounter some problems when I use the dataset. I appreciate any help you can provide.

1. As reported in the manuscript, the number of unique contents is 38,811. However, 35,499 videos in the labels_train_test.csv plus 3,573 videos in the labels_test_1080p.csv is 39,072, which is not equal to the given number in the paper. Thus, could you please help me figure out which one is the correct number, or maybe there is something I missed or understood incorrectly?
2. In the published labels_train_test.csv, I notice that the frame number of some videos (from the row 35,241 to the end) are 0 or 1 that the duration of these video are not 5-12s. I am wondering whether these videos belong to the LSVQ dataset.

Best regards

**Comment by baidut** [comment]
Hi, @h4nwei  Thank you for reaching out 🥰
**The number in the paper is correct**. There are some broken videos that should have been removed.
We have reuploaded the updated file. 

Thank you for your sharp eye 👀✨!

**Comment by jiangtaoo2333** [comment]
hello，可以共享下lsvq数据集么，box下载链接的密码一直没收到。
